version: "3.8"

services:
  mysql:
    container_name: mysql
    image:  mysql:8.0.37
    restart: unless-stopped
    env_file:
      - .\backend\.env
    environment:
      - MYSQL_DATABASE={$DB_NAME} # Specifies the name of the database
      - MYSQL_PASSWORD={$DB_PASSWORD} # Sets the password for the MySQL user
      - MYSQL_ROOT_PASSWORD={$DB_PASSWORD} # Sets the root password for MySQL
    networks:
      - sameNetworkAsMysql
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    build:
      context: ./backend # Specifies the build context directory for the backend
      dockerfile: dockerfile # Specifies the Dockerfile to use for building the backend
    container_name: esm-backend-container
    ports:
      - "5000:5000"
    # environment:
    #   - DB_HOST=mysql
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_NAME=${DB_NAME}
    #   - DB_PORT=${DB_PORT}
    #   - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: esm-frontend-container
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    depends_on:
      - backend # Specifies that the 'frontend' service depends on the 'backend' service

networks:
  sameNetworkAsMysql: # Defines the 'sameNetworkAsMysql' network
    driver: bridge # Specifies the network driver as 'bridge'

volumes:
  db: